.\"
.\" $Id: uuniq.1,v 1.2 2012/05/30 10:43:00 urs Exp $
.\"
.TH UUNIQ 1 "Apr 28, 2012" "" "User Commands"
.SH NAME
uuniq \- remove duplicate lines from input
.SH SYNOPSIS
.B uuniq
.RB [ \-i ]
.RI [ file " ...]"
.SH DESCRIPTION
.B uuniq
reads lines from input and copies them to standard output with duplicate
lines removed.  For each set of identical lines only the first occurence
is written to output.  This is similar to
.BR uniq (1),
but in contrast,
.B uuniq
does not require the input lines to be sorted.
.SH OPTIONS
.TP
.B \-i
Ignore case when comparing lines.
.SH "SEE ALSO"
.BR uniq (1)
.SH AUTHOR
Urs Thuermann <urs@isnogud.escape.de>
